# Generated by Django 4.0.6 on 2022-08-04 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_name', models.CharField(max_length=100, verbose_name='Industry Name')),
                ('industry_description', models.TextField(verbose_name='Industry Description')),
            ],
            options={
                'verbose_name': 'Industry List',
                'verbose_name_plural': 'Industry Lists',
            },
        ),
        migrations.CreateModel(
            name='JobApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_company', models.CharField(max_length=150, verbose_name='Job Company')),
                ('job_title', models.CharField(max_length=200, verbose_name='Job Title')),
                ('job_description', models.TextField(verbose_name='Job Description')),
                ('contract_type', models.CharField(blank=True, choices=[('FT', 'Full Time'), ('PT', 'Part Time'), ('CO', 'Contract'), ('IN', 'Internship'), ('NO', 'Not Specified'), ('OT', 'Other')], default='FT', max_length=2, null=True, verbose_name='Contract Type')),
                ('job_location', models.CharField(max_length=300, verbose_name='Job Location')),
                ('other_industry', models.CharField(blank=True, max_length=200, null=True, verbose_name='Other Industry')),
                ('other_profession', models.CharField(blank=True, max_length=200, null=True, verbose_name='Other Profession')),
                ('salary_type', models.CharField(blank=True, choices=[('MO', 'Monthly'), ('YR', 'Yearly'), ('DY', 'Daily'), ('HR', 'Hourly'), ('NO', 'Not Specified'), ('OT', 'Other')], default='MO', max_length=2, null=True, verbose_name='Salary Type')),
                ('job_salary_currency', djmoney.models.fields.CurrencyField(choices=[('CLP', 'Chilean Peso'), ('USD', 'US Dollar')], default='CLP', editable=False, max_length=3, null=True)),
                ('job_salary', djmoney.models.fields.MoneyField(decimal_places=2, max_digits=10, null=True, verbose_name='Salary')),
                ('job_created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('app_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
                ('job_industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.industrylist', verbose_name='Industry')),
            ],
            options={
                'verbose_name': 'Job Application',
                'verbose_name_plural': 'Job Applications',
            },
        ),
        migrations.CreateModel(
            name='Professions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=200, verbose_name='Area Name')),
                ('area_description', models.TextField(verbose_name='Area Description')),
            ],
            options={
                'verbose_name': 'Knowledge Area',
                'verbose_name_plural': 'Knowledge Areas',
            },
        ),
        migrations.CreateModel(
            name='ReminderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('INT', 'Interview'), ('CALL', 'Call'), ('EMAIL', 'Correo electrónico'), ('OTHER', 'Other')], default='INT', max_length=10, verbose_name='Type')),
                ('reminder_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10, verbose_name='Status')),
                ('reminder_description', models.TextField(verbose_name='Description')),
                ('reminder_date', models.DateField(verbose_name='Date')),
                ('reminder_time', models.TimeField(verbose_name='Hora')),
                ('reminder_contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Name')),
                ('reminder_contact_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Number')),
                ('reminder_contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('reminder_notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('reminder_url', models.URLField(blank=True, null=True, verbose_name='Optional Link')),
                ('parent_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.jobapplications', verbose_name='Job')),
            ],
            options={
                'verbose_name': 'Reminder Model',
                'verbose_name_plural': 'Reminder Models',
            },
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='job_profession',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_app.professions', verbose_name='Profession'),
        ),
    ]
